const quotes = [
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs", category: "motivational" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde", category: "motivational" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein", category: "motivational" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", category: "motivational" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon", category: "life" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama", category: "happiness" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West", category: "life" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan", category: "dreams" },
  { text: "Spread love everywhere you go.", author: "Mother Teresa", category: "love" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "love" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", category: "dreams" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson", category: "motivational" },
  { text: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein", category: "motivational" },
  { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost", category: "life" },
  { text: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain", category: "wisdom" },
  { text: "A friend is someone who knows all about you and still loves you.", author: "Elbert Hubbard", category: "friendship" },
  { text: "To live is the rarest thing in the world. Most people just exist.", author: "Oscar Wilde", category: "life" },
  { text: "Darkness cannot drive out darkness; only light can do that.", author: "Martin Luther King Jr.", category: "motivational" },
  { text: "We accept the love we think we deserve.", author: "Stephen Chbosky", category: "love" },
  { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien", category: "motivational" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot", category: "motivational" },
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi", category: "motivational" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", category: "motivational" },
  { text: "Small daily improvements are the key to staggering long-term results.", author: "Robin Sharma", category: "motivational" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", category: "motivational" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", category: "success" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "motivational" },
  { text: "We know what we are, but know not what we may be.", author: "William Shakespeare", category: "motivational" },
  { text: "Live in the sunshine, swim the sea, drink the wild air.", author: "Ralph Waldo Emerson", category: "life" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama", category: "happiness" },
  { text: "First they ignore you, then they ridicule you, then they fight you, and then you win.", author: "Mahatma Gandhi", category: "motivational" },
  { text: "Two roads diverged in a wood, and I took the one less traveled by.", author: "Robert Frost", category: "motivational" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey", category: "motivational" },
  { text: "Every child is an artist. The problem is how to remain an artist once he grows up.", author: "Pablo Picasso", category: "motivational" },
  { text: "You can never cross the ocean until you have the courage to lose sight of the shore.", author: "Christopher Columbus", category: "courage" },
  { text: "I've learned that people will never forget how you made them feel.", author: "Maya Angelou", category: "motivational" },
  { text: "Either you run the day, or the day runs you.", author: "Jim Rohn", category: "motivational" },
  { text: "Whether you think you can or you think you can't, you are right.", author: "Henry Ford", category: "motivational" },
  { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain", category: "life" },
  { text: "Whatever the mind of man can conceive and believe, it can achieve.", author: "Napoleon Hill", category: "wisdom" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein", category: "success" },
  { text: "The mind is everything. What you think you become.", author: "Buddha", category: "wisdom" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra", category: "success" },
  { text: "People who are crazy enough to think they can change the world are the ones who do.", author: "Rob Siltanen", category: "motivational" },
  { text: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino", category: "success" },
  { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou", category: "motivational" },
  { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Johann Wolfgang von Goethe", category: "motivational" },
  { text: "We generate fears while we sit. We overcome them by action.", author: "Dr. Henry Link", category: "motivational" },
  { text: "Security is mostly a superstition. Life is either a daring adventure or nothing.", author: "Helen Keller", category: "life" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", category: "motivational" },
  { text: "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", author: "Winston Churchill", category: "motivational" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers", category: "motivational" },
  { text: "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you.", author: "Steve Jobs", category: "motivational" },
  { text: "People rarely succeed unless they have fun in what they are doing.", author: "Dale Carnegie", category: "success" },
  { text: "There is no substitute for hard work.", author: "Thomas Edison", category: "perseverance" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi", category: "motivational" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi", category: "motivational" },
  { text: "Try to be a rainbow in someone else's cloud.", author: "Maya Angelou", category: "perseverance" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", category: "motivational" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt", category: "motivational" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin", category: "motivational" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown", category: "motivational" },
  { text: "Great things never come from comfort zones.", author: "Unknown", category: "motivational" },
  { text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown", category: "success" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown", category: "perseverance" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown", category: "motivational" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown", category: "perseverance" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery", category: "motivational" },
  { text: "It's going to be hard, but hard does not mean impossible.", author: "Unknown", category: "motivational" },
  { text: "Don't wait for opportunity. Create it.", author: "Unknown", category: "motivational" },
  { text: "The key to success is to focus on goals, not obstacles.", author: "Unknown", category: "success" },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston", category: "motivational" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar", category: "motivational" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun", category: "motivational" },
  { text: "Your only limit is your mind.", author: "Unknown", category: "wisdom" },
  { text: "Work hard in silence, let your success be the noise.", author: "Frank Ocean", category: "success" },
  { text: "Be so good they can't ignore you.", author: "Steve Martin", category: "motivational" },
  { text: "The secret of success is to do the common things uncommonly well.", author: "John D. Rockefeller", category: "success" },
  { text: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney", category: "courage" },
  { text: "Talent wins games, but teamwork and intelligence win championships.", author: "Michael Jordan", category: "motivational" },
  { text: "I never dreamed about success, I worked for it.", author: "Estée Lauder", category: "success" },
  { text: "Don't limit your challenges. Challenge your limits.", author: "Jerry Dunn", category: "motivational" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis", category: "dreams" },
  { text: "It is not the mountain we conquer, but ourselves.", author: "Sir Edmund Hillary", category: "motivational" },
  { text: "Only I can change my life. No one can do it for me.", author: "Carol Burnett", category: "life" },
  { text: "The harder the conflict, the more glorious the triumph.", author: "Thomas Paine", category: "motivational" },
  { text: "If you can dream it, you can do it.", author: "Walt Disney", category: "dreams" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", category: "motivational" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin", category: "perseverance" },
  { text: "Genius is one percent inspiration, ninety-nine percent perspiration.", author: "Thomas Edison", category: "motivational" },
  { text: "You just can't beat the person who never gives up.", author: "Babe Ruth", category: "motivational" },
  { text: "The starting point of all achievement is desire.", author: "Napoleon Hill", category: "motivational" },
  { text: "A winner is a dreamer who never gives up.", author: "Nelson Mandela", category: "motivational" },
  { text: "Vision without execution is just hallucination.", author: "Henry Ford", category: "motivational" },
  { text: "If you want to achieve greatness, stop asking for permission.", author: "Unknown", category: "motivational" },
  { text: "To live a creative life, we must lose our fear of being wrong.", author: "Joseph Chilton Pearce", category: "life" },
  { text: "If you are not willing to learn, no one can help you. If you are determined to learn, no one can stop you.", author: "Zig Ziglar", category: "perseverance" },
  { text: "We are all here for some special reason. Stop being a prisoner of your past. Become the architect of your future.", author: "Robin Sharma", category: "motivational" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James", category: "motivational" },
  { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett", category: "success" },
  { text: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt", category: "motivational" },
  { text: "Always remember that you are absolutely unique. Just like everyone else.", author: "Margaret Mead", category: "motivational" },
  { text: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson", category: "motivational" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi", category: "motivational" },
  { text: "Winning isn't everything, but wanting to win is.", author: "Vince Lombardi", category: "motivational" },
  { text: "You have to expect things of yourself before you can do them.", author: "Michael Jordan", category: "motivational" },
  { text: "Once you choose hope, anything is possible.", author: "Christopher Reeve", category: "motivational" },
  { text: "You can do anything, but not everything.", author: "David Allen", category: "motivational" },
  { text: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi", category: "motivational" },
  { text: "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", author: "Maya Angelou", category: "life" },
  { text: "If opportunity doesn't knock, build a door.", author: "Milton Berle", category: "motivational" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", category: "motivational" },
  { text: "An unexamined life is not worth living.", author: "Socrates", category: "life" },
  { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa", category: "love" },
  { text: "When you stand at the edge of all the light you know and are about to step off into the darkness of the unknown, faith is knowing one of two things will happen.", author: "Patrick Overton", category: "motivational" },
  { text: "The most common form of despair is not being who you are.", author: "Soren Kierkegaard", category: "motivational" },
  { text: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln", category: "life" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth", category: "courage" },
  { text: "Money and success don't change people; they merely amplify what is already there.", author: "Will Smith", category: "success" },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs", category: "life" },
  { text: "Not how long, but how well you have lived is the main thing.", author: "Seneca", category: "motivational" },
  { text: "Dost thou love life? Then do not squander time, for that is the stuff life is made of.", author: "Benjamin Franklin", category: "love" },
  { text: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", author: "Anne Frank", category: "motivational" },
  { text: "You may say I'm a dreamer, but I'm not the only one.", author: "John Lennon", category: "motivational" },
  { text: "The real test is not whether you avoid this failure, because you won't. It's whether you let it harden or shame you into inaction.", author: "Barack Obama", category: "motivational" },
  { text: "Every strike brings me closer to the next home run.", author: "Babe Ruth", category: "motivational" },
  { text: "Definiteness of purpose is the starting point of all achievement.", author: "W. Clement Stone", category: "motivational" },
  { text: "A people that values its privileges above its principles soon loses both.", author: "Dwight D. Eisenhower", category: "motivational" },
  { text: "If your ship doesn't come in, swim out to meet it.", author: "Jonathan Winters", category: "motivational" },
  { text: "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.", author: "Marie Curie", category: "motivational" },
  { text: "Problems are not stop signs, they are guidelines.", author: "Robert H. Schuller", category: "motivational" },
  { text: "One way to keep momentum going is to have constantly greater goals.", author: "Michael Korda", category: "dreams" },
  { text: "Learn from the mistakes of others. You can't live long enough to make them all yourself.", author: "Eleanor Roosevelt", category: "life" },
  { text: "Press forward. Do not stop, do not linger in your journey, but strive for the mark set before you.", author: "George Whitefield", category: "motivational" },
  { text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh", category: "motivational" },
  { text: "No bird soars too high if he soars with his own wings.", author: "William Blake", category: "motivational" },
  { text: "A goal is a dream with a deadline.", author: "Napoleon Hill", category: "dreams" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill", category: "success" },
  { text: "Just don't give up trying to do what you really want to do.", author: "Ella Fitzgerald", category: "motivational" },
  { text: "It is not what you look at that matters, it is what you see.", author: "Henry David Thoreau", category: "motivational" },
  { text: "The secret to getting ahead is getting started.", author: "Agatha Christie", category: "motivational" },
  { text: "You've gotta dance like there's nobody watching.", author: "William W. Purkey", category: "motivational" },
  { text: "Challenges are what make life interesting and overcoming them is what makes life meaningful.", author: "Joshua J. Marine", category: "life" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington", category: "motivational" },
  { text: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply.", author: "Leonardo da Vinci", category: "motivational" },
  { text: "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.", author: "Jamie Paolinetti", category: "life" },
  { text: "You take your life in your own hands, and what happens? A terrible thing: no one to blame.", author: "Erica Jong", category: "life" },
  { text: "What's money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.", author: "Bob Dylan", category: "success" },
  { text: "I didn't fail the test. I just found 100 ways to do it wrong.", author: "Benjamin Franklin", category: "motivational" },
  { text: "In order to succeed, your desire for success should be greater than your fear of failure.", author: "Bill Cosby", category: "success" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", category: "perseverance" },
  { text: "The person who says it cannot be done should not interrupt the person who is doing it.", author: "Chinese Proverb", category: "motivational" },
  { text: "There are two ways of spreading light: to be the candle or the mirror that reflects it.", author: "Edith Wharton", category: "motivational" },
  { text: "Happiness is not something you postpone for the future; it is something you design for the present.", author: "Jim Rohn", category: "happiness" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill", category: "motivational" },
  { text: "We become what we think about.", author: "Earl Nightingale", category: "motivational" },
  { text: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", author: "Mark Twain", category: "motivational" },
  { text: "Life shrinks or expands in proportion to one's courage.", author: "Anais Nin", category: "life" },
  { text: "If you want to make your dreams come true, the first thing you have to do is wake up.", author: "J.M. Power", category: "dreams" },
  { text: "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.", author: "Booker T. Washington", category: "motivational" },
  { text: "Certain things catch your eye, but pursue only those that capture the heart.", author: "Ancient Indian Proverb", category: "love" },
  { text: "Believe and act as if it were impossible to fail.", author: "Charles Kettering", category: "motivational" },
  { text: "I can't imagine a person becoming a success who doesn't give this game of life everything he's got.", author: "Walter Cronkite", category: "life" },
  { text: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand", category: "motivational" },
  { text: "Keep your eyes on the stars and your feet on the ground.", author: "Theodore Roosevelt", category: "motivational" },
  { text: "To accomplish great things, we must not only act, but also dream; not only plan, but also believe.", author: "Anatole France", category: "dreams" },
  { text: "Without hard work, nothing grows but weeds.", author: "Gordon B. Hinckley", category: "perseverance" },
  { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon", category: "success" },
  { text: "Motivation is the art of getting people to do what you want them to do because they want to do it.", author: "Dwight D. Eisenhower", category: "motivational" },
  { text: "Make each day your masterpiece.", author: "John Wooden", category: "motivational" },
  { text: "You were born to win, but to be a winner you must plan to win, prepare to win, and expect to win.", author: "Zig Ziglar", category: "motivational" },
  { text: "Creativity is intelligence having fun.", author: "Albert Einstein", category: "motivational" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson", category: "motivational" },
  { text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett", category: "love" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", category: "motivational" },
  { text: "Nothing in life is to be feared, it is only to be understood.", author: "Marie Curie", category: "life" },
  { text: "The best way to predict the future is to invent it.", author: "Alan Kay", category: "motivational" },
  { text: "Our greatest glory is not in never failing, but in rising up every time we fail.", author: "Ralph Waldo Emerson", category: "motivational" },
  { text: "All things are difficult before they are easy.", author: "Thomas Fuller", category: "motivational" },
  { text: "The will to win, the desire to succeed, the urge to reach your full potential — these are the keys that will unlock the door to personal excellence.", author: "Confucius", category: "success" },
  { text: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", author: "Johann Wolfgang Von Goethe", category: "motivational" },
  { text: "We aim above the mark to hit the mark.", author: "Ralph Waldo Emerson", category: "motivational" },
  { text: "There is nothing impossible to him who will try.", author: "Alexander the Great", category: "perseverance" },
  { text: "The human spirit needs to accomplish, to achieve, to triumph to be happy.", author: "Ben Stein", category: "happiness" },
  { text: "Courage is resistance to fear, mastery of fear, not absence of fear.", author: "Mark Twain", category: "courage" },
  { text: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart", category: "motivational" },
  { text: "You become what you believe.", author: "Oprah Winfrey", category: "motivational" },
  { text: "Nothing is impossible, the word itself says 'I'm possible'.", author: "Audrey Hepburn", category: "motivational" },
  { text: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", author: "Martin Luther King Jr.", category: "motivational" },
  { text: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson", category: "motivational" },
  { text: "Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein", category: "success" },
  { text: "The only way to do great work is to love what you do. If you haven't found it yet, keep looking.", author: "Steve Jobs", category: "love" },
  { text: "You must not lose faith in humanity. Humanity is an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty.", author: "Mahatma Gandhi", category: "motivational" },
  { text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas Edison", category: "success" },
  { text: "Where there is a will, there is a way. If there is a chance in a million that you can do something, anything, to keep what you want from ending, do it.", author: "Pauline Kael", category: "motivational" },
  { text: "When something is important enough, you do it even if the odds are not in your favor.", author: "Elon Musk", category: "motivational" },
  { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson", category: "perseverance" },
  { text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou", category: "success" },
  { text: "If you're offered a seat on a rocket ship, don't ask what seat. Just get on.", author: "Sheryl Sandberg", category: "motivational" },
  { text: "Someday is not a day of the week.", author: "Janet Dailey", category: "motivational" },
  { text: "Happiness is a butterfly, which when pursued, is always just beyond your grasp, but which, if you will sit down quietly, may alight upon you.", author: "Nathaniel Hawthorne", category: "happiness" },
  { text: "The most wasted of days is one without laughter.", author: "E.E. Cummings", category: "happiness" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau", category: "life" },
  { text: "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left.", author: "Erma Bombeck", category: "life" },
  { text: "Few are those who see with their own eyes and feel with their own hearts.", author: "Albert Einstein", category: "motivational" },
  { text: "If you obey all the rules, you miss all the fun.", author: "Katharine Hepburn", category: "motivational" },
  { text: "What we achieve inwardly will change outer reality.", author: "Plutarch", category: "motivational" },
  { text: "The only way out of the labyrinth of suffering is to forgive.", author: "John Green", category: "motivational" },
  { text: "Don't cry because it's over, smile because it happened.", author: "Dr. Seuss", category: "motivational" },
  { text: "You've got to jump off cliffs and build your wings on the way down.", author: "Ray Bradbury", category: "motivational" },
  { text: "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.", author: "Neil Gaiman", category: "motivational" },
  { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller", category: "life" },
  { text: "It does not matter how slowly you go, as long as you do not stop.", author: "Confucius", category: "motivational" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair", category: "courage" },
  { text: "The question is not who is going to let me; it is who is going to stop me.", author: "Ayn Rand", category: "motivational" },
  { text: "Success is determined not by whether or not you face obstacles, but by your reaction to them.", author: "Benjamin Carson", category: "success" },
  { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis", category: "motivational" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot", category: "motivational" },
  { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt", category: "motivational" },
  { text: "I alone cannot change the world, but I can cast a stone across the water to create many ripples.", author: "Mother Teresa", category: "motivational" },
  { text: "Nothing is impossible. The word itself says 'I'm possible'!", author: "Audrey Hepburn", category: "motivational" },
  { text: "To see what is right and not do it is a lack of courage.", author: "Confucius", category: "courage" },
  { text: "Reading is to the mind what exercise is to the body.", author: "Joseph Addison", category: "wisdom" },
  { text: "You may encounter many defeats, but you must not be defeated.", author: "Maya Angelou", category: "motivational" },
  { text: "Remember no one can make you feel inferior without your consent.", author: "Eleanor Roosevelt", category: "motivational" },
  { text: "Don't settle for what life gives you; make life better and build something.", author: "Ashton Kutcher", category: "life" },
  { text: "Reality is wrong. Dreams are for real.", author: "Tupac Shakur", category: "dreams" },
  { text: "To infinity and beyond!", author: "Buzz Lightyear", category: "motivational" },
  { text: "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", author: "Bill Keane", category: "motivational" },
  { text: "From what we get, we can make a living; what we give, however, makes a life.", author: "Arthur Ashe", category: "life" },
  { text: "It is not what you look at that matters, it is what you see.", author: "Henry David Thoreau", category: "motivational" },
  { text: "The more that you read, the more things you will know.", author: "Dr. Seuss", category: "motivational" },
  { text: "The true meaning of life is to plant trees, under whose shade you do not expect to sit.", author: "Nelson Henderson", category: "life" },
  { text: "If you want happiness for an hour, take a nap. If you want happiness for a day, go fishing. If you want happiness for a year, inherit a fortune. If you want happiness for a lifetime, help somebody.", author: "Chinese Proverb", category: "happiness" },
  { text: "Build your own dreams, or someone else will hire you to build theirs.", author: "Farrah Gray", category: "dreams" },
  { text: "The battles that count aren't the ones for gold medals. The struggles within yourself — the invisible, inevitable battles inside all of us — that's where it's at.", author: "Jesse Owens", category: "motivational" },
  { text: "Education costs money. But then so does ignorance.", author: "Sir Claus Moser", category: "motivational" },
  { text: "I have learned over the years that when one's mind is made up, this diminishes fear.", author: "Rosa Parks", category: "wisdom" },
  { text: "It's not the size of the dog in the fight, it's the size of the fight in the dog.", author: "Mark Twain", category: "motivational" },
  { text: "Necessity is the mother of invention.", author: "Plato", category: "motivational" },
  { text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi", category: "motivational" },
  { text: "We must accept finite disappointment, but never lose infinite hope.", author: "Martin Luther King Jr.", category: "motivational" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson", category: "motivational" },
  { text: "You don't make progress by standing on the sidelines, whimpering and complaining. You make progress by implementing ideas.", author: "Shirley Chisholm", category: "motivational" },
  { text: "Stay afraid, but do it anyway. What's important is the action. You don't have to wait to be confident.", author: "Carrie Fisher", category: "courage" },
  { text: "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", author: "Aristotle", category: "motivational" },
  { text: "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.", author: "Jesus Christ", category: "motivational" },
  { text: "The secret to happiness is freedom, and the secret to freedom is courage.", author: "Thucydides", category: "happiness" },
  { text: "I couldn't wait for success, so I went ahead without it.", author: "Jonathan Winters", category: "success" },
  { text: "Don't be satisfied with stories, how things have gone with others. Unfold your own myth.", author: "Rumi", category: "motivational" },
  { text: "Out of difficulties grow miracles.", author: "Jean de la Bruyere", category: "motivational" },
  { text: "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.", author: "Mark Caine", category: "success" },
  { text: "People become really quite remarkable when they start thinking that they can do things.", author: "Norman Vincent Peale", category: "motivational" },
  { text: "Your big opportunity may be right where you are now.", author: "Napoleon Hill", category: "motivational" },
  { text: "Great achievement is usually born of great sacrifice, and is never the result of selfishness.", author: "Napoleon Hill", category: "motivational" },
  { text: "If you don't value your time, neither will others. Stop giving away your time and talents.", author: "Kim Garst", category: "motivational" },
  { text: "When you know what you want, and want it bad enough, you'll find a way to get it.", author: "Jim Rohn", category: "motivational" },
  { text: "Whenever you see a successful person, you only see the public glories, never the private sacrifices to reach them.", author: "Vaibhav Shah", category: "motivational" },
  { text: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", author: "Thomas Edison", category: "perseverance" },
  { text: "Successful entrepreneurs are givers and not takers of positive energy.", author: "Anonymous", category: "motivational" },
  { text: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden", category: "motivational" },
  { text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou", category: "motivational" },
  { text: "To be great is to be misunderstood.", author: "Ralph Waldo Emerson", category: "motivational" },
  { text: "There are no traffic jams along the extra mile.", author: "Roger Staubach", category: "motivational" },
  { text: "True nobility is being superior to your former self.", author: "Ernest Hemingway", category: "motivational" },
  { text: "Even if you're on the right track, you'll get run over if you just sit there.", author: "Will Rogers", category: "motivational" },
  { text: "People often say that motivation doesn't last. Well, neither does bathing — that's why we recommend it daily.", author: "Zig Ziglar", category: "motivational" },
  { text: "Everything should be made as simple as possible, but not simpler.", author: "Albert Einstein", category: "motivational" },
  { text: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", author: "David Brinkley", category: "motivational" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt", category: "motivational" },
  { text: "I used to want the words 'She tried' on my tombstone. Now I want 'She did it.'", author: "Katherine Dunham", category: "perseverance" },
  { text: "Whatever you want in life, other people are going to want it too. Believe in yourself enough to accept the idea that you have an equal right to it.", author: "Diane Sawyer", category: "life" },
  { text: "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", author: "Henry Ford", category: "life" },
  { text: "If you ask me what I came into this life to do, I will tell you: I came to live out loud.", author: "Emile Zola", category: "life" },
  { text: "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.", author: "Helen Keller", category: "happiness" },
  { text: "I will go anywhere as long as it is forward.", author: "David Livingston", category: "motivational" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali", category: "motivational" },
  { text: "To live will be an awfully big adventure.", author: "Peter Pan", category: "life" },
  { text: "You must expect great things of yourself before you can do them.", author: "Michael Jordan", category: "motivational" },
  { text: "It takes 20 years to build a reputation and five minutes to ruin it.", author: "Warren Buffett", category: "motivational" },
  { text: "There is nothing more beautiful than someone who goes out of their way to make life beautiful for others.", author: "Mandy Hale", category: "life" },
  { text: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", author: "Vince Lombardi", category: "wisdom" },
  { text: "I don't regret the things I've done, I regret the things I didn't do when I had the chance.", author: "Unknown", category: "motivational" },
  { text: "Put your heart, mind, and soul into even your smallest acts. This is the secret of success.", author: "Swami Sivananda", category: "love" },
  { text: "The more I want to get something done, the less I call it work.", author: "Richard Bach", category: "perseverance" },
  { text: "Success is the sum of small efforts, repeated day-in and day-out.", author: "Robert Collier", category: "success" },
  { text: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown", category: "life" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison", category: "perseverance" },
  { text: "A man is not finished when he is defeated. He is finished when he quits.", author: "Richard Nixon", category: "motivational" },
  { text: "Try to be a rainbow in someone's cloud.", author: "Maya Angelou", category: "perseverance" },
  { text: "Learn as if you will live forever, live like you will die tomorrow.", author: "Mahatma Gandhi", category: "life" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth", category: "courage" },
  { text: "Real difficulties can be overcome; it is only the imaginary ones that are unconquerable.", author: "Theodore N. Vail", category: "motivational" },
  { text: "I believe that if one always looked at the skies, one would end up with wings.", author: "Gustave Flaubert", category: "motivational" },
  { text: "You may be disappointed if you fail, but you are doomed if you don't try.", author: "Beverly Sills", category: "perseverance" },
  { text: "We know what we are but know not what we may be.", author: "William Shakespeare", category: "motivational" },
  { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon", category: "success" },
  { text: "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", author: "Plato", category: "life" },
  { text: "Efforts and courage are not enough without purpose and direction.", author: "John F. Kennedy", category: "courage" },
  { text: "Give me a lever long enough and a fulcrum on which to place it, and I shall move the world.", author: "Archimedes", category: "motivational" },
  { text: "It is not enough to have a good mind; the main thing is to use it well.", author: "Rene Descartes", category: "wisdom" },
  { text: "Great things are done by a series of small things brought together.", author: "Vincent Van Gogh", category: "motivational" },
  { text: "Keep your face always toward the sunshine and shadows will fall behind you.", author: "Walt Whitman", category: "motivational" },
  { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale", category: "motivational" },
  { text: "Be not afraid of greatness; some are born great, some achieve greatness, and others have greatness thrust upon them.", author: "William Shakespeare", category: "courage" },
  { text: "If you want to be happy, set a goal that commands your thoughts, liberates your energy and inspires your hopes.", author: "Andrew Carnegie", category: "happiness" },
  { text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali", category: "life" },
  { text: "Success means doing the best we can with what we have. Success is the doing, not the getting; in the trying, not the triumph.", author: "Wynn Davis", category: "success" },
  { text: "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", author: "Jimmy Dean", category: "motivational" },
  { text: "Impossible is just an opinion.", author: "Paulo Coelho", category: "motivational" },
  { text: "You are the sum total of everything you've ever seen, heard, eaten, smelled, been told, forgot — it's all there.", author: "Maya Angelou", category: "motivational" },
  { text: "When I was 5 years old, my mother always told me that happiness was the key to life.", author: "John Lennon", category: "happiness" },
  { text: "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.", author: "Henry Ford", category: "motivational" },
  { text: "It's not what you look at that matters, it's what you see.", author: "Henry David Thoreau", category: "motivational" },
  { text: "The only way to discover the limits of the possible is to go beyond them into the impossible.", author: "Arthur C. Clarke", category: "motivational" },
  { text: "The dreamers are the saviors of the world.", author: "James Allen", category: "motivational" },
  { text: "Protect your enthusiasm from the negativity and fear of others.", author: "H. Jackson Brown Jr.", category: "courage" },
  { text: "Success is getting what you want, happiness is wanting what you get.", author: "W.P. Kinsella", category: "happiness" },
  { text: "The biggest adventure you can ever take is to live the life of your dreams.", author: "Oprah Winfrey", category: "life" },
  { text: "With self-discipline, most anything is possible.", author: "Theodore Roosevelt", category: "motivational" },
  { text: "The more you lose yourself in something bigger than yourself, the more energy you will have.", author: "Norman Vincent Peale", category: "motivational" },
  { text: "Perseverance is the hard work you do after you get tired of doing the hard work you already did.", author: "Newt Gingrich", category: "perseverance" },
  { text: "Work like there is someone working twenty-four hours a day to take it all away from you.", author: "Mark Cuban", category: "perseverance" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb", category: "motivational" },
  { text: "Never give up, for that is just the place and time that the tide will turn.", author: "Harriet Beecher Stowe", category: "perseverance" },
  { text: "When we strive to become better than we are, everything around us becomes better too.", author: "Paulo Coelho", category: "motivational" },
  { text: "Learning is not attained by chance; it must be sought for with ardor and attended to with diligence.", author: "Abigail Adams", category: "motivational" },
  { text: "The distance between insanity and genius is measured only by success.", author: "Bruce Feirstein", category: "success" },
  { text: "The first and greatest victory is to conquer yourself.", author: "Plato", category: "motivational" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar", category: "dreams" },
  { text: "It's not the mountain we conquer but ourselves.", author: "Edmund Hillary", category: "motivational" },
  { text: "Risk more than others think is safe. Dream more than others think is practical.", author: "Howard Schultz", category: "dreams" },
  { text: "The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves to the task at hand.", author: "Vince Lombardi", category: "success" },
  { text: "A winner is a dreamer who never gives up.", author: "Nelson Mandela", category: "motivational" },
  { text: "To accomplish great things, we must not only act but also dream.", author: "Anatole France", category: "dreams" },
  { text: "Know yourself. Don't accept your dog's admiration as conclusive evidence that you are wonderful.", author: "Ann Landers", category: "motivational" },
  { text: "Excellence is not a destination but a continuous journey that never ends.", author: "Brian Tracy", category: "motivational" },
  { text: "The wisest mind has something yet to learn.", author: "George Santayana", category: "wisdom" },
  { text: "I'd rather regret the things I've done than regret the things I haven't done.", author: "Lucille Ball", category: "motivational" },
  { text: "We become who we are by what we do.", author: "Aristotle", category: "motivational" },
  { text: "Seize the day, and put the least possible trust in tomorrow.", author: "Horace", category: "motivational" },
  { text: "What would you do if you weren't afraid?", author: "Sheryl Sandberg", category: "courage" },
  { text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis", category: "success" },
  { text: "The only source of knowledge is experience.", author: "Albert Einstein", category: "wisdom" },
  { text: "Conformity is the jailer of freedom and the enemy of growth.", author: "John F. Kennedy", category: "motivational" },
  { text: "You can't fall if you don't climb. But there's no joy in living your whole life on the ground.", author: "Unknown", category: "happiness" },
  { text: "We do not need magic to transform our world. We carry all of the power we need inside ourselves already.", author: "J.K. Rowling", category: "motivational" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", category: "life" },
  { text: "You don't have to be perfect to be amazing.", author: "Unknown", category: "motivational" },
  { text: "Life is what we make it, always has been, always will be.", author: "Grandma Moses", category: "life" },
  { text: "Life's a climb, but the view is great.", author: "Miley Cyrus", category: "life" },
  { text: "The flower that blooms in adversity is the rarest and most beautiful of all.", author: "Mulan", category: "motivational" },
  { text: "You have to be odd to be number one.", author: "Dr. Seuss", category: "motivational" },
  { text: "The less you respond to negative people, the more peaceful your life will become.", author: "Unknown", category: "life" },
  { text: "A ship in harbor is safe, but that is not what ships are built for.", author: "John A. Shedd", category: "motivational" },
  { text: "I am thankful for all of those who said NO to me. It's because of them I'm doing it myself.", author: "Albert Einstein", category: "motivational" },
  { text: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop", category: "motivational" },
  { text: "If you're not stubborn, you'll give up on experiments too soon.", author: "Jeff Bezos", category: "motivational" },
  { text: "The best gift anyone can give, I believe, is the gift of sharing themselves.", author: "Oprah Winfrey", category: "motivational" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King", category: "motivational" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou", category: "perseverance" },
  { text: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", author: "Dr. Seuss", category: "motivational" },
  { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer", category: "happiness" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs", category: "motivational" },
  { text: "The only person you should try to be better than is who you were yesterday.", author: "Unknown", category: "perseverance" },
  { text: "If you genuinely want something, don't wait for it — teach yourself to be impatient.", author: "Gurbaksh Chahal", category: "motivational" },
  { text: "You have to learn the rules of the game. And then you have to play better than anyone else.", author: "Albert Einstein", category: "motivational" },
  { text: "Never let your memories be greater than your dreams.", author: "Doug Ivester", category: "dreams" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe", category: "motivational" },
  { text: "The best way out is always through.", author: "Robert Frost", category: "motivational" },
  { text: "In the long run, we shape our lives, and we shape ourselves.", author: "Eleanor Roosevelt", category: "life" },
  { text: "The key is not the will to win — everybody has that. It is the will to prepare to win that is important.", author: "Bobby Knight", category: "motivational" },
  { text: "Excellence is to do a common thing in an uncommon way.", author: "Booker T. Washington", category: "motivational" },
  { text: "You get what you work for, not what you wish for.", author: "Unknown", category: "perseverance" },
  { text: "If opportunity doesn't knock, build a door.", author: "Kurt Cobain", category: "motivational" },
  { text: "Good things come to people who wait, but better things come to those who go out and get them.", author: "Unknown", category: "motivational" },
  { text: "Every accomplishment starts with the decision to try.", author: "John F. Kennedy", category: "perseverance" },
  { text: "Aspire to inspire before you expire.", author: "Unknown", category: "motivational" },
  { text: "It's not about how bad you want it. It's about how hard you're willing to work for it.", author: "Unknown", category: "perseverance" },
  { text: "Work until your idols become your rivals.", author: "Unknown", category: "perseverance" },
  { text: "The man who has confidence in himself gains the confidence of others.", author: "Hasidic Proverb", category: "motivational" },
  { text: "Self-belief and hard work will always earn you success.", author: "Virat Kohli", category: "success" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes", category: "motivational" },
  { text: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn", category: "motivational" },
  { text: "To succeed in life, you need two things: ignorance and confidence.", author: "Mark Twain", category: "life" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle", category: "motivational" },
  { text: "It's always too soon to quit.", author: "Norman Vincent Peale", category: "motivational" },
  { text: "Every day is a chance to be better.", author: "Unknown", category: "motivational" },
  { text: "Take risks in your life. If you win, you can lead; if you lose, you can guide.", author: "Swami Vivekananda", category: "life" },
  { text: "The best dreams happen when you're awake.", author: "Cherie Gilderbloom", category: "dreams" },
  { text: "Success is doing ordinary things extraordinarily well.", author: "Jim Rohn", category: "success" },
  { text: "Dream it. Believe it. Build it.", author: "Unknown", category: "dreams" },
  { text: "Where there is no struggle, there is no strength.", author: "Oprah Winfrey", category: "motivational" },
  { text: "Chase the vision, not the money; the money will end up following you.", author: "Tony Hsieh", category: "motivational" },
  { text: "Don't wait. The time will never be just right.", author: "Napoleon Hill", category: "motivational" },
  { text: "A creative man is motivated by the desire to achieve, not by the desire to beat others.", author: "Ayn Rand", category: "motivational" },
  { text: "Make improvements, not excuses. Seek respect, not attention.", author: "Roy T. Bennett", category: "motivational" },
  { text: "He who conquers himself is the mightiest warrior.", author: "Confucius", category: "motivational" },
  { text: "The secret of life is honesty and fair dealing. If you can fake that, you've got it made.", author: "Groucho Marx", category: "life" },
  { text: "Better to remain silent and be thought a fool than to speak out and remove all doubt.", author: "Abraham Lincoln", category: "motivational" },
  { text: "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.", author: "J.K. Rowling", category: "motivational" },
  { text: "Do not take life too seriously. You will never get out of it alive.", author: "Elbert Hubbard", category: "life" },
  { text: "We live in a rainbow of chaos.", author: "Paul Cezanne", category: "life" },
  { text: "The purpose of life is a life of purpose.", author: "Robert Byrne", category: "life" },
  { text: "The aim of life is self-development. To realize one's nature perfectly — that is what each of us is here for.", author: "Oscar Wilde", category: "life" },
  { text: "You've got to get up every morning with determination if you're going to go to bed with satisfaction.", author: "George Horace Lorimer", category: "perseverance" },
  { text: "Be gentle to all and stern with yourself.", author: "Saint Teresa of Avila", category: "motivational" },
  { text: "You make mistakes. Mistakes don't make you.", author: "Maxwell Maltz", category: "motivational" },
  { text: "The truth is you don't know what is going to happen tomorrow. Life is a crazy ride, and nothing is guaranteed.", author: "Eminem", category: "wisdom" },
  { text: "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.'", author: "Mary Anne Radmacher", category: "courage" },
];

// ==========================================================
// CATEGORY -> BACKGROUND IMAGE MAP
// Replace these placeholder paths with your own images later.
// Just drop your image files into an "images" folder next to
// this script and update the path here. Filenames can be
// anything you like as long as the path matches.
// ==========================================================
const categoryBackgrounds = {
  motivational: "motivational.jpg",
  life:         "life.jpg",
  success:      "success.jpg",
  perseverance: "perseverance.jpg",
  dreams:       "dreams.jpg",
  happiness:    "happiness.jpg",
  courage:      "courage.jpg",
  wisdom:       "wisdom.jpg",
  love:         "love.jpg",
  friendship:   "friendship.jpg"
};

// Fallback image if a category somehow has no mapped image
const defaultBackground = "happiness.jpg";

// Keeps track of the currently applied background so we don't
// reapply (and re-trigger the fade) when the category hasn't changed
let currentBackground = null;

function updateBackground(category) {
  const imagePath = categoryBackgrounds[category] || defaultBackground;
  if (imagePath === currentBackground) return; // no change, skip
  currentBackground = imagePath;

  // Fade out, swap image, fade back in
  document.body.style.opacity = "0";
  setTimeout(() => {
    document.body.style.backgroundImage = `url(${imagePath})`;
    document.body.style.opacity = "1";
  }, 400);
}

let currentIndex = 0;
let favorites = JSON.parse(localStorage.getItem('favQuotes')) || [];

const quoteText = document.querySelector('.quote-text');
const quoteAuthor = document.querySelector('.quote-author');
const btnPrev = document.getElementById('btn-prev');
const btnNext = document.getElementById('btn-next');
const btnFav = document.getElementById('btn-fav');
const btnCopy = document.getElementById('btn-copy');
const btnShare = document.getElementById('btn-share');

function showQuote(index) {
  quoteText.textContent = '\u201C' + quotes[index].text + '\u201D';
  quoteAuthor.textContent = '- ' + quotes[index].author;
  updateBackground(quotes[index].category);
  updateFavBtn();
}

function updateFavBtn() {
  const isFav = favorites.includes(currentIndex);
  btnFav.textContent = isFav ? '\u2764\uFE0F Saved' : '\u2764 Fav';
}

btnNext.addEventListener('click', () => {
  currentIndex = (currentIndex + 1) % quotes.length;
  showQuote(currentIndex);
});

btnPrev.addEventListener('click', () => {
  currentIndex = (currentIndex - 1 + quotes.length) % quotes.length;
  showQuote(currentIndex);
});

btnFav.addEventListener('click', () => {
  if (favorites.includes(currentIndex)) {
    favorites = favorites.filter(i => i !== currentIndex);
  } else {
    favorites.push(currentIndex);
  }
  localStorage.setItem('favQuotes', JSON.stringify(favorites));
  updateFavBtn();
});

btnCopy.addEventListener('click', () => {
  const text = quotes[currentIndex].text + ' - ' + quotes[currentIndex].author;
  navigator.clipboard.writeText(text).then(() => {
    btnCopy.textContent = '✅ Copied!';
    setTimeout(() => { btnCopy.textContent = '📋 Copy'; }, 2000);
  });
});

btnShare.addEventListener('click', () => {
  const text = '\u201C' + quotes[currentIndex].text + '\u201D - ' + quotes[currentIndex].author;
  if (navigator.share) {
    navigator.share({ title: 'Daily Quote', text: text });
  } else {
    const url = 'https://wa.me/?text=' + encodeURIComponent(text);
    window.open(url, '_blank');
  }
});

showQuote(currentIndex);
